services:
  db:
    image: postgres:15-alpine
    container_name: ${DOCKER_CONTAINER:-komaru}-db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /opt/${DOCKER_CONTAINER}/postgres_data:/var/lib/postgresql/data
    networks:
      - komaru-network

  redis:
    image: redis:8.6-alpine
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - komaru-network

  bot:
    build: 
      context: .
      args:
        - APP_DIR=/opt/${DOCKER_CONTAINER}
    container_name: ${DOCKER_CONTAINER:-komaru}-bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/opt/${DOCKER_CONTAINER}  # ВАЖНО: Монтируем текущую папку, чтобы git pull работал с реальными файлами
    environment:
      - DB_HOST=db
      - DOCKER_CONTAINER=${DOCKER_CONTAINER:-komaru}-bot
    networks:
      - komaru-network

networks:
  komaru-network:
    driver: bridge